# For test deployments on my mac
version: "3.9"
services:
  app:
    platform: "linux/arm64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: daftdove/ezfind:latest
    environment:
      - DATABASE_URL=postgresql://lucaszheng:lucaszheng@host.docker.internal:5432/ez-find-db
