version: "3.9"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=${CMP_PG_USER}
      - POSTGRES_PASSWORD=${CMP_PG_PW}
      - POSTGRES_DB=${CMP_PG_DB}
    volumes:
      - db:/var/lib/postgresql/data
  app:
    user: root
    depends_on:
      - db
    image: daftdove/ezfind:latest
    platform: "linux/arm64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${CMP_PG_USER}:${CMP_PG_PW}@db:5432/${CMP_PG_DB}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_ID=${GOOGLE_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
volumes:
  db:
    driver: local
# NOTE: DATABASE_URL=postgresql://USER:PASSWORD@HOST:PORT/DATABASE?schema=SCHEMA
